name: 'Generate Docs'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    name: Generate Docs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2

      - run: ./deploy/generate_docs.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs [no ci]
